# ----- CONFIG -----
@host=http://localhost:3000
@token= Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYyNTM4NzkwNiwiZXhwIjoxNjI1Mzg4ODA2fQ.OsnNRrFSHHFSoSY_eqirciXAyupLyufUEmJ8ZW4Pf-Y

# ----- QUERIES -----
# hello
@qHello=query { hello }
# login
@qLogin=mutation { login(email:"chondan@hotmail.com", password:"chondan") { accessToken } }
# bye
@qBye=query { bye }

# ----- GraphQL Endpoint ----- 
POST {{host}}/graphql
Authorization: {{token}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{{qLogin}}

###

# ----- REFRESH TOKEN ROUTE -----
# *** REST Client remember Cookies for subsequent requests ***
POST {{host}}/refresh_token